/*
 * Application for displaing and manipulating of DBF and XLS files
 *
 * Copyright (C) 2009-2011 Dmytro Starzhynskyi (dvstar)
 * http://swirl.sourceforge.net/
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/*
 * ExelExportDialog.java
 *
 * Created on 21 січ 2011, 12:46:11
 */

package net.sf.dvstar.swirl.desktopdbf;

import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 *
 * @author dstarzhynskyi
 */
public class ExelExportDialog extends javax.swing.JDialog {
    private boolean resultDialog = false;
    private ExportParamsResult result = new ExportParamsResult();
    private final ResourceMap globalResourceMap;


    /** Creates new form ExelExportDialog */
    public ExelExportDialog() {
        
        super();
        initComponents();
        globalResourceMap = Application.getInstance(DesktopDBFApp.class).getContext().getResourceMap(ExelExportDialog.class);
        this.setIconImage(globalResourceMap.getImageIcon("MainFrame.icon").getImage());
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbFileType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbFileEncoding = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tfStructure = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfSkipLine = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfReplaceFrom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfReplaceTo = new javax.swing.JTextField();
        chDefineStruct = new javax.swing.JCheckBox();
        chOpenFile = new javax.swing.JCheckBox();
        tfOutputFile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btSelectFile = new javax.swing.JButton();
        chReplace = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btNo = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(net.sf.dvstar.swirl.desktopdbf.DesktopDBFApp.class).getContext().getResourceMap(ExelExportDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 460));
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 42));

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setForeground(resourceMap.getColor("jLabel8.foreground")); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(460, 380));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cbFileType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dbf File", "Csv File" }));
        cbFileType.setName("cbFileType"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        cbFileEncoding.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CP1125", "MC1251", "KOI8-U", "UTF-8" }));
        cbFileEncoding.setName("cbFileEncoding"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        tfStructure.setText(resourceMap.getString("tfStructure.text")); // NOI18N
        tfStructure.setName("tfStructure"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        tfSkipLine.setText(resourceMap.getString("tfSkipLine.text")); // NOI18N
        tfSkipLine.setName("tfSkipLine"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        tfReplaceFrom.setText(resourceMap.getString("tfReplaceFrom.text")); // NOI18N
        tfReplaceFrom.setName("tfReplaceFrom"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        tfReplaceTo.setText(resourceMap.getString("tfReplaceTo.text")); // NOI18N
        tfReplaceTo.setName("tfReplaceTo"); // NOI18N

        chDefineStruct.setSelected(true);
        chDefineStruct.setText(resourceMap.getString("chDefineStruct.text")); // NOI18N
        chDefineStruct.setName("chDefineStruct"); // NOI18N

        chOpenFile.setText(resourceMap.getString("chOpenFile.text")); // NOI18N
        chOpenFile.setName("chOpenFile"); // NOI18N

        tfOutputFile.setText(resourceMap.getString("tfOutputFile.text")); // NOI18N
        tfOutputFile.setName("tfOutputFile"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        btSelectFile.setIcon(resourceMap.getIcon("btSelectFile.icon")); // NOI18N
        btSelectFile.setText(resourceMap.getString("btSelectFile.text")); // NOI18N
        btSelectFile.setName("btSelectFile"); // NOI18N
        btSelectFile.setPreferredSize(new java.awt.Dimension(120, 29));

        chReplace.setText(resourceMap.getString("chReplace.text")); // NOI18N
        chReplace.setName("chReplace"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chDefineStruct, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFileType, 0, 178, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFileEncoding, 0, 178, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfStructure, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSkipLine, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfReplaceFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfReplaceTo, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(tfOutputFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(btSelectFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFileEncoding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chDefineStruct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStructure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSkipLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addComponent(chReplace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(tfReplaceFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfReplaceTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chOpenFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 46));

        btOk.setIcon(resourceMap.getIcon("btOk.icon")); // NOI18N
        btOk.setText(resourceMap.getString("btOk.text")); // NOI18N
        btOk.setName("btOk"); // NOI18N
        btOk.setPreferredSize(new java.awt.Dimension(120, 29));
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btNo.setIcon(resourceMap.getIcon("btNo.icon")); // NOI18N
        btNo.setText(resourceMap.getString("btNo.text")); // NOI18N
        btNo.setName("btNo"); // NOI18N
        btNo.setPreferredSize(new java.awt.Dimension(120, 29));
        btNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        resultDialog = true;
        
        result.fileExportTypeDefs = cbFileType.getSelectedItem().toString();
        result.fileExportType = result.makeExportType(result.fileExportTypeDefs);
        result.fileExportEncodeDefs = cbFileEncoding.getSelectedItem().toString();
        result.fileExportEncode = result.makeEncode(result.fileExportEncodeDefs);
        result.structLine = Integer.parseInt( tfStructure.getText() );
        result.skipLine = Integer.parseInt( tfSkipLine.getText() );

        result.replaceChar = chReplace.isSelected();
        result.defineStruct = chDefineStruct.isSelected();
        result.openExportFile = chOpenFile.isSelected();
        
        result.replaceCharFrom = tfReplaceFrom.getText();
        result.replaceCharTo = tfReplaceTo.getText();

        this.dispose();
    }//GEN-LAST:event_btOkActionPerformed

    private void btNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoActionPerformed
        // TODO add your handling code here:
        resultDialog = false;
        this.dispose();
    }//GEN-LAST:event_btNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNo;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btSelectFile;
    private javax.swing.JComboBox cbFileEncoding;
    private javax.swing.JComboBox cbFileType;
    private javax.swing.JCheckBox chDefineStruct;
    private javax.swing.JCheckBox chOpenFile;
    private javax.swing.JCheckBox chReplace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfOutputFile;
    private javax.swing.JTextField tfReplaceFrom;
    private javax.swing.JTextField tfReplaceTo;
    private javax.swing.JTextField tfSkipLine;
    private javax.swing.JTextField tfStructure;
    // End of variables declaration//GEN-END:variables

    public boolean getOk() {
        return resultDialog;
    }

    /**
     * @return the result
     */
    public ExportParamsResult getResult() {
        return result;
    }


    public static class ExportParamsResult {
        public String fileExportTypeDefs;
        public int    fileExportType;
        public String fileExportEncodeDefs;
        public int    fileExportEncode;


        public String fileExportName;

        public String replaceCharFrom;
        public String replaceCharTo;

        public int structLine;
        public int skipLine;

        public boolean replaceChar;
        public boolean openExportFile;
        public boolean defineStruct;

        public static final int EXPORT_TYPE_CSV = 1;
        public static final int EXPORT_TYPE_DBF = 2;
        
        public static final int ENCODE_UTF8 = 1;
        public static final int ENCODE_CP1125 = 2;
        public static final int ENCODE_CP1251 = 3;

        public static final String ENCODE_DEF_UTF8   = "-UTF8";
        public static final String ENCODE_DEF_CP1125 = "-CP1125";
        public static final String ENCODE_DEF_CP1251 = "-CP1251";

        @Override
        public String toString(){

            return "["+fileExportName+"]["+fileExportTypeDefs+"]["+fileExportEncodeDefs+"]["+structLine+"]["+skipLine+"]"+
                    "["+replaceCharFrom+"]["+replaceCharTo+"]["+replaceChar+"]["+openExportFile+"]";

        }

        public int makeExportType(String fileExportTypeDefs) {
            int ret=EXPORT_TYPE_CSV;
            if(fileExportTypeDefs.contains("Dbf")) ret = EXPORT_TYPE_DBF;
            return ret;
        }

        public int makeEncode(String fileExportEncodeDefs) {
            int ret=ENCODE_UTF8;
            if(fileExportEncodeDefs.contains("1125")) ret = ENCODE_CP1125;
            if(fileExportEncodeDefs.contains("1251")) ret = ENCODE_CP1251;
            return ret;
        }
    }

}
